#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
# Generates flade's bundled cutscene-flute soundfont: a minimal SoundFont 2 with
# a single instrument on GM program 74 (Recorder), which is the only instrument
# the LBA1 FLA cutscene MIDI (MIDI_MI.HQR entry 26) ever uses. The waveform is a
# sine fundamental plus faint 2nd/3rd harmonics (additive synthesis) - a clean,
# slightly breathy flute tone - looped over an exact number of cycles so the loop
# is seamless. No external samples, so the result is ours to license (GPL/CC0).
#
#   tools/make_flute_sf2.py src/flute_sf2.h   # regenerate the embedded C array
#   tools/make_flute_sf2.py flute.sf2         # or a raw .sf2 (for --soundfont)
import struct, math, sys

SR, ROOT, NCYC = 44100, 69, 44          # A4 = 440 Hz
LEN = SR * NCYC // 440                   # 4410 samples = 44 cycles -> seamless loop
HARMONICS = [1.0, 0.12, 0.04]            # fundamental, 2nd (octave), 3rd (twelfth)

samp = []
for i in range(LEN):
    th = 2 * math.pi * 440 * i / SR
    samp.append(sum(a * math.sin((n + 1) * th) for n, a in enumerate(HARMONICS)))
peak = max(abs(x) for x in samp)
pcm = b''.join(struct.pack('<h', int(x / peak * 0.62 * 32767)) for x in samp)
pcm += b'\x00\x00' * 46                  # SF2 needs >=46 zero samples after the sample


def chunk(tag, d):
    return tag + struct.pack('<I', len(d)) + d + (b'\x00' if len(d) % 2 else b'')


def lst(typ, *cs):
    b = typ + b''.join(cs)
    return b'LIST' + struct.pack('<I', len(b)) + b


def z(s, n):
    return s.encode()[:n - 1].ljust(n, b'\x00')


def gen(op, amt):
    return struct.pack('<Hh', op, amt) if amt < 0 else struct.pack('<HH', op, amt)


info = lst(b'INFO', chunk(b'ifil', struct.pack('<HH', 2, 1)),
           chunk(b'isng', b'EMU8000\x00'), chunk(b'INAM', b'flade flute\x00'))
sdta = lst(b'sdta', chunk(b'smpl', pcm))

# instrument zone: keyRange first, sampleID last
gens = [(43, 127 << 8), (34, -5573), (38, -3284), (54, 1), (58, ROOT), (53, 0)]
igen = b''.join(gen(o, a) for o, a in gens) + gen(0, 0)
phdr = z('Flute', 20) + struct.pack('<HHHIII', 74, 0, 0, 0, 0, 0) + \
    z('EOP', 20) + struct.pack('<HHHIII', 0, 0, 1, 0, 0, 0)
pbag = struct.pack('<HH', 0, 0) + struct.pack('<HH', 1, 0)
pgen = gen(41, 0) + gen(0, 0)
inst = z('Flute', 20) + struct.pack('<H', 0) + z('EOI', 20) + struct.pack('<H', 1)
ibag = struct.pack('<HH', 0, 0) + struct.pack('<HH', len(gens), 0)
shdr = z('Flute', 20) + struct.pack('<IIIIIBbHH', 0, LEN, 0, LEN, SR, ROOT, 0, 0, 1) + \
    z('EOS', 20) + struct.pack('<IIIIIBbHH', 0, 0, 0, 0, 0, 0, 0, 0, 0)
pdta = lst(b'pdta', chunk(b'phdr', phdr), chunk(b'pbag', pbag), chunk(b'pmod', b'\x00' * 10),
           chunk(b'pgen', pgen), chunk(b'inst', inst), chunk(b'ibag', ibag),
           chunk(b'imod', b'\x00' * 10), chunk(b'igen', igen), chunk(b'shdr', shdr))
body = b'sfbk' + info + sdta + pdta
sf2 = b'RIFF' + struct.pack('<I', len(body)) + body

out = sys.argv[1]
if out.endswith('.h'):
    with open(out, 'w') as f:
        f.write("/* SPDX-License-Identifier: GPL-2.0-only\n"
                " * Copyright (C) 2026 the flade authors\n"
                " * Generated by tools/make_flute_sf2.py - do not edit by hand.\n"
                " * A minimal SoundFont 2 (GM program 74) for the FLA cutscene flute. */\n"
                "#ifndef FLADE_FLUTE_SF2_H\n#define FLADE_FLUTE_SF2_H\n\n"
                "static const unsigned char flute_sf2[] = {\n")
        for i in range(0, len(sf2), 16):
            f.write("    " + ",".join("0x%02x" % b for b in sf2[i:i + 16]) + ",\n")
        f.write("};\nstatic const unsigned int flute_sf2_len = %d;\n\n"
                "#endif /* FLADE_FLUTE_SF2_H */\n" % len(sf2))
    print("wrote %s (%d-byte soundfont, GM program 74)" % (out, len(sf2)))
else:
    open(out, 'wb').write(sf2)
    print("wrote %s (%d bytes, GM program 74)" % (out, len(sf2)))
